### PR TITLE
More JavaScript in Web Syllabus

### PR DESCRIPTION
**Pull request by trandthanh**
- Changes the import of Bootstrap

### CODE REVIEW

**Comment by ajdubovoy** [comment]
@Eschults OK if we merge this also? Doing so would resolve https://github.com/lewagon/teachers/issues/1628

**Comment by Eschults** [comment]
Good question! Do we need to merge `master` in [`no-update`](https://github.com/lewagon/rails-stylesheets/tree/no-update) first?

**Comment by ajdubovoy** [comment]
@juliends if I understand correctly I don't think any batches are operating on it anymore so we should be good?

**Comment by Eschults** [comment]
We still have a handful of PT batches on `no-update` 👇 

Screen Shot 2023-08-30 at 18 28 12

**Comment by meleu** [comment]
The deletion of the `more-js` branch is causing issues with the `minimal.rb` template (rails-template repo).

[Details in the issue here.](https://github.com/lewagon/rails-templates/issues/154)

Probably [this Pull Request](https://github.com/lewagon/rails-templates/pull/155) will fix it.

**Comment by juliends** [comment]
> The deletion of the `more-js` branch is causing issues with the `minimal.rb` template (rails-template repo).
> 
> [Details in the issue here.](https://github.com/lewagon/rails-templates/issues/154)
> 
> Probably [this Pull Request](https://github.com/lewagon/rails-templates/pull/155) will fix it.

Tanks for the fix 🙏

**Pull request merged**
